### ISSUE TITLE
"Please use idf.py only in an ESP-IDF shell environment."

### ISSUE THREAD

**Issue by ibarrick** [mirrexagon/nixpkgs-esp-dev#24]
After overriding the version to 5.1 (I have an h2 chip and need support for that), I get this error every time I run idf.py: 

"Please use idf.py only in an ESP-IDF shell environment."

This is apparently an error printed by esp-idf if it fails to import something but I cannot for the life of me understand why anything would be different when changing the version. All the imports in that try...except block are the same in 5.0.2.

https://github.com/espressif/esp-idf/blob/5181de8ac5ec5e18f04f634da8ce173b7ef5ab73/tools/idf.py#L46

**Comment by mirrexagon** [comment]
After updating the Python packages and ESP-IDF, I can build for ESP32-C6 and ESP32-H2, and flash ESP32-C6 (I have no H2 board to test with, unfortunately).

Let me know if this doesn't solve the problem.
