### ISSUE TITLE
"CMakeLists.txt not found" when running idf.py

### ISSUE THREAD

**Issue by jonahbron** [mirrexagon/nixpkgs-esp-dev#48]
I'm running a develop shell directly from the flake ref as in the readme, but when I try to run an idf.py command, I get an error:

```
$ idf.py erase-flash
Executing action: erase-flash
CMakeLists.txt not found in project directory /home/jonah
```

Am I missing a step here?  FWIW, that path is _not_ a Git repo.

**Comment by mksafavi** [comment]
idf.py commands only work in idf project directories.

**Comment by mirrexagon** [comment]
I expect this isn't a bug in this project, so I will close.
