### ISSUE TITLE
parttool.py is not available on bin path

### ISSUE THREAD

**Issue by mksafavi** [mirrexagon/nixpkgs-esp-dev#58]
Some of the idf tools are inside the `/components` directory and they are symlinked to /bin/.
Maybe we should add them

on esp-idf docker image:
```
$ whereis parttool
parttool: /opt/esp/idf/components/partition_table/parttool.py
$ whereis parttool.py
parttool: /opt/esp/idf/components/partition_table/parttool.py
```
They can be accessed like this on nixpkgs-esp-dev:
```
$IDF_PATH/components/partition_table/parttool.py
$IDF_PATH/components/spiffs/spiffsgen.py
```

**Comment by mirrexagon** [comment]
Do you know how the Docker container has this set up? I'm looking in the Dockerfile and `idf_tools.py` to try and figure it out so we can do it the same way, but I haven't seen anything so far.

**Comment by mirrexagon** [comment]
I found that `export.sh` does this:

```sh
    IDF_ADD_PATHS_EXTRAS="${IDF_PATH}/components/espcoredump"
    IDF_ADD_PATHS_EXTRAS="${IDF_ADD_PATHS_EXTRAS}:${IDF_PATH}/components/partition_table"
    IDF_ADD_PATHS_EXTRAS="${IDF_ADD_PATHS_EXTRAS}:${IDF_PATH}/components/app_update"
```

So I will do that in the ESP-IDF setup hook.
